FROM python:3.9-slim
WORKDIR /app
RUN pip install pandas kafka-python sqlalchemy psycopg2-binary
COPY . .
# On lance ton script consumer (vérifie bien le nom exact du fichier)
CMD ["python", "consumer_to_minio.py"]